### ISSUE TITLE
Shared game logic

### ISSUE THREAD

**Issue by TOByrne** [TOByrne/Connect4#3]
Move the Winning Move logic out of the mediator, so it's easily accessible to the Players.  (I have something in progress that I can commit later.)

**Comment by ManuelDeLeon** [comment]
I don't think we should do this. It would mean we're responsible for creating an efficient algorithm for detecting win situations. That's something the player should do.

**Comment by asherjvitek** [comment]
I see your point but, I think if a person does not like the performance of the default and then choose to implement their own they can if they so desire.

**Comment by TOByrne** [comment]
Performance considerations aside, it ensures that all players can play according to the exact same (unit-tested) win-conditions and it's ultimately no different than someone copy/pasting the code into their own Player.

**Comment by ManuelDeLeon** [comment]
I'm very much against it. It's at the heart of the whole exercise. The developer should come up with an (efficient) algorithm to figure out if they're going to win the game with a particular move.

If that's not enough, here's another argument: by providing a helper method to players you're actually steering the design of their code to match that of your helper method.

**Comment by TOByrne** [comment]
I disagree, but:

I want to move the win-checking out of the mediator anyway; The mediator has gotten kinda sloppy.

I can maintain the existing accessibility, so there's no net change, forcing Players to either write their own win-checks or to write their own Facade and hijack the methods in the same manner as the [unit tests](https://github.com/TOByrne/Connect4/blob/master/C4Mediator.Tests/TestMediator.cs) - this way there's the explicit intent to use the existing stuff at the possible expense of their own Player.

Mutually agreeable?

**Comment by asherjvitek** [comment]
I am cool with this.
